movieapp/movieapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mywebsite/',include('mywebsite.urls')),
    path('',include('django.contrib.auth.urls')),
    
    
]

movieapp/mywebsite/urls.py
from django.urls import path
from.import views

app_name = 'mywebsite'

urlpatterns = [
    path('',views.imdb_top_100,name='imdbtop'),#bora.com/mywebsite/commentpage
    path('whattowatch/',views.whattowatch,name='whattowatch'),#bora.com/mywebsite/movies
    path('comentpage/',views.commentpage,name='commentpage'),#bora.com/mywebsite/commentpage
    path('intheaters/',views.intheaters,name='intheaters'),#bora.com/mywebsite/intheaters
    
    path('addcomment/<int:movie_id>/', views.addcomment, name='addcomment'),#bora.com/mywebsite/addcomment
    path('signup/',views.signUpView.as_view(),name="signup"),
    path('deletecomment/<int:id>',views.deletecomment,name="deletecomment"),
    path("movieinfo/<int:id>",views.movieinfo,name = "movieinfo"),
    
    
    
    
    
    
   
]

movieapp/mywebsite/models.py
from django.db import models
from django.contrib.auth.models import User

class Movie(models.Model):
    title = models.CharField(max_length=200)
    imdb_id = models.CharField(max_length=50, unique=True)
    poster_url = models.URLField(max_length=500, blank=True, null=True)
    

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    rating = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.rating}'

movieapp/mywebsite/views.py
import random
from tokenize import Comment
from django.shortcuts import get_object_or_404, render,redirect
from . import models
from django.urls import reverse,reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
import requests
from .models import Comment




# Create your views here.
def commentpage(request):
    all_comments = Comment.objects.all()  # Comment modelini kullanıyoruz
    comment_dictionary = {"comments": all_comments}
    return render(request, 'mywebsite/commentpage.html', context=comment_dictionary)


@login_required
def addcomment(request, movie_id):
    if request.method == "POST":
        user = request.user
        comment = request.POST["comment"]
        rating = request.POST["rating"]
        Comment.objects.create(user=user, comment_text=comment, rating=rating, movie_id=movie_id)
        return redirect(reverse('mywebsite:commentpage'))
    else:
        return render(request, 'mywebsite/addcomment.html', {'movie_id': movie_id})




@login_required
def deletecomment(request,id):
    comment = models.Comment.objects.get(pk=id)
    if request.user == comment.user:
        models.Comment.objects.filter(id=id).delete()
        return redirect("mywebsite:commentpage")
        
def whattowatch(request):
    api_key = 'YOUR_API_KEY'
    base_url = 'https://api.themoviedb.org/3/movie/'

    def get_random_movie():
        randomID = random.randint(1, 10000)
        params = {
            'api_key': api_key,
            'language': 'en-US',
        }
        response = requests.get(base_url + str(randomID), params=params)
        movie = response.json()
        
        if response.status_code == 200 and movie.get('status_code') is None and movie.get('poster_path'):
            return movie
        return None

    movie = None
    while movie is None:
        movie = get_random_movie()

    return render(request, 'mywebsite/whattowatch.html', {'movie': movie})

def intheaters(request):
    api_key = 'YOUR_API_KEY'
    base_url = 'https://api.themoviedb.org/3/movie/upcoming'
    params = {
        'api_key': api_key,
        'language': 'en-US',
        'page': 1
    }
    
    movies = []
    for page in range(1,3): 
        params['page'] = page
        response = requests.get(base_url, params=params)
        data = response.json()
        movies.extend(data.get('results', []))

    return render(request, 'mywebsite\inTheaters.html', {'movies': movies})
    

def movieinfo(request,id):
    movie_id = id
    api_key = 'YOUR_API_KEY'  
    base_url = f'https://api.themoviedb.org/3/movie/{movie_id}'
    params = {
        'api_key': api_key,
        'language': 'en-US',
    }
    
    response = requests.get(base_url, params=params)
    movie = response.json()
    print(movie)

    return render(request, 'mywebsite/movieinfo.html', {'movie': movie})


class signUpView(CreateView):
    
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"
    
def imdb_top_100(request):
    api_key = 'YOUR_API_KEY'
    base_url = 'https://api.themoviedb.org/3/movie/top_rated'
    params = {
        'api_key': api_key,
        'language': 'en-US',
        'page': 1
    }
    
    movies = []
    for page in range(1, 6): 
        params['page'] = page
        response = requests.get(base_url, params=params)
        data = response.json()
        movies.extend(data.get('results', []))

    return render(request, 'mywebsite/imdbtop.html', {'movies': movies})

movieapp/mywebsite/templates/mywebsite/addcomment.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <section style='background-image: url("{% static "mywebsite/images/bg.jpg" %}"); background-size:cover'>
        <div class="container my-5 py-5 text-body">
            <div class="row d-flex justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-6">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="d-flex flex-start w-100">
                                <img class="rounded-circle shadow-1-strong me-3"
                                    src="https://api.multiavatar.com/{{ movie_id }}.png" alt="Avatar" width="65"
                                    height="65" />
                                <div class="w-100">
                                    
                                    <input type="hidden" name="movie_id" value="{{ movie_id }}">
                                    
                                    <h5>Add a comment</h5>
                                    <div class="form-outline">
                                        <label class="form-label" for="comment_text">What is your view?</label>
                                        <textarea class="form-control" id="comment_text" name="comment" rows="4" style="border-color: black;"></textarea>
                                    </div>
                                    <fieldset class="rating mt-3">
                                        <legend>Rate The Film</legend>
                                        <input type="radio" id="star5" name="rating" value="5" />
                                        <label class="fa fa-star" for="star5"></label>
                                        <input type="radio" id="star4" name="rating" value="4" />
                                        <label class="fa fa-star" for="star4"></label>
                                        <input type="radio" id="star3" name="rating" value="3" />
                                        <label class="fa fa-star" for="star3"></label>
                                        <input type="radio" id="star2" name="rating" value="2" />
                                        <label class="fa fa-star" for="star2"></label>
                                        <input type="radio" id="star1" name="rating" value="1" />
                                        <label class="fa fa-star" for="star1"></label>
                                    </fieldset>
                                    <div class="d-flex justify-content-between mt-3">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>
{% endblock %}

movieapp/mywebsite/templates/mywebsite/commentpage.html
{% extends "base.html" %}

{% block content %}

<style>
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: 'Mulish', sans-serif;
        transition: 0.3s all ease-in-out;
    }
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background-color: #F0F2FB; 
        margin-top: 60px; 
    }
    .comments-container {
        border-radius: 5px;
        padding: 20px;
        background-color: #FFF; 
        width: 80%;
        max-width: 800px; 
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .comment-item {
        display: flex;
        align-items: flex-start;
        margin-bottom: 20px;
        padding: 15px;
        border: 1px solid #DAE1F5; 
        border-radius: 4px;
    }
    .comment-item img {
        border-radius: 50%; 
        margin-right: 15px;
        width: 65px;
        height: 65px; 
        object-fit: cover; 
    }
    .comment-item .text-content {
        flex: 1;
    }
    .comment-item p {
        margin-bottom: 10px;
        color: #545D7A; 
    }
    .comment-item p:first-of-type {
        font-weight: 700;
        color: #10182F; 
    }
    .btn-delete {
        margin-top: 10px;
        color: #fff;
        background-color: #dc3545;
        border: none;
        padding: 5px 10px;
        border-radius: 4px;
        text-decoration: none;
        font-size: 14px;
    }
</style>

<div class="comments-container">
    <ul>
        {% for comment in comments %}
        <li class="comment-item">
            <img src="https://api.multiavatar.com/{{ comment.id }}.png" alt="Avatar">
            <div class="text-content">
                <p>{{ comment.user }} / {{comment.movie_id}}</p>
                <p>{{ comment.comment_text }}</p>
                <p>Rating: {{ comment.rating }}</p>
                {% if comment.user == user %}
                <a href="{% url 'mywebsite:deletecomment' comment.id %}" class="btn-delete">Delete</a>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

movieapp/mywebsite/templates/mywebsite/imdbtop.html
{% extends "base.html" %}

{% block content %}

<h2 style="text-align: center; margin-bottom: 20px;">IMDB TOP 100 MOVIES</h2>

<style>
body {
    font-family: Arial, sans-serif;
    background-color: #f5f5f5;
    color: #333;
    margin: 0;
    padding: 0;
}

h2 {
    font-size: 2em;
    color: #333;
}

.movie-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    padding: 20px;
}

.movie-card {
    background: #fff;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    width: 200px;
    text-align: center;
    transition: transform 0.3s;
}

.movie-card:hover {
    transform: scale(1.05);
}

.movie-poster {
    width: 100%;
    height: auto;
    border-bottom: 2px solid #eee;
}

.movie-title {
    padding: 10px;
    background-color: #fff;
}

.movie-title p {
    margin: 0;
    font-size: 1em;
    color: #333;
}
</style>

<div class="movie-container">
    {% for movie in movies %}
        <a href="{%url 'mywebsite:movieinfo' id=movie.id%}" class="movie-card">
    <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie.title }}" class="movie-poster">
    <div class="movie-title">
        <p>{{ movie.title }}</p>
    </div>
</a>
    {% endfor %}
</div>

{% endblock %}

movieapp/mywebsite/templates/mywebsite/inTheaters.html
{%extends "base.html"%}

{%block content%}
<br><br><br><br><br><br>

<h2 style="text-align: center; margin-bottom: 20px;">Upcoming Movies</h2>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
        color: #333;
        margin: 0;
        padding: 0;
    }
    
    h2 {
        font-size: 2em;
        color: #333;
    }
    
    .movie-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 20px;
        padding: 20px;
    }
    
    .movie-card {
        background: #fff;
        border-radius: 10px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        width: 200px;
        text-align: center;
        transition: transform 0.3s;
    }
    
    .movie-card:hover {
        transform: scale(1.05);
    }
    
    .movie-poster {
        width: 100%;
        height: auto;
        border-bottom: 2px solid #eee;
    }
    
    .movie-title {
        padding: 10px;
        background-color: #fff;
    }
    
    .movie-title p {
        margin: 0;
        font-size: 1em;
        color: #333;
    }
    </style>
    <div class="movie-container">
        {% for movie in movies %}
            <a href="{%url 'mywebsite:movieinfo' id=movie.id%}" class="movie-card">
            <div class="movie-card">
                <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie.title }}" class="movie-poster">
                <div class="movie-title">
                    <p>{{ movie.title }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{%endblock%}

movieapp/mywebsite/templates/mywebsite/movieinfo.html
{% extends "base.html" %}

{% block content %}
<br><br><br><br><br><br>

<h2 style="text-align: center; margin-bottom: 20px;">Movie Info</h2>

<div style="position: relative; display: flex; align-items: flex-start; gap: 20px; padding: 20px;">
    <!-- Poster -->
    <div style="flex-shrink: 0;">
        <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie.title }}" style="max-width: 300px; border-radius: 10px;">
    </div>
    
    <!-- Film Bilgileri -->
    <div style="flex-grow: 1; position: relative;"> 
        <h3>{{ movie.title }}</h3>
        <p><strong>Release Date:</strong> {{ movie.release_date }}</p>
        <p><strong>Rating:</strong> {{ movie.vote_average }} / 10</p>
        <p><strong>Overview:</strong> {{ movie.overview }}</p>
        <br><br><br><br><br><br><br>
        
        <!-- Buton -->
        <button type="button" class="btn btn-success" 
        {% if user.is_authenticated %}
            onclick="window.location.href='{% url 'mywebsite:addcomment' movie_id=movie.id %}'"
        {% else %}
            onclick="window.location.href='{% url 'login' %}'"
        {% endif %}
        style="position: absolute; bottom: 0; right: 60px;">
        {% if user.is_authenticated %}
        Add a comment
        {% else %}
            Please log in to comment
        {% endif %}
        </button>
    </div>
</div>

{% endblock %}

movieapp/mywebsite/templates/mywebsite/whattowatch.html
{%extends "base.html"%}

{%block content%}
<br><br><br><br><br><br>

<h2>WHAT TO WATCH</h2>
{%endblock%}

movieapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="basestyle.css">
    <style>
      
      
      .rating {
          direction: rtl;
          unicode-bidi: bidi-override;
      }
      .rating input[type="radio"] {
          display: none;
      }
      .rating label {
          font-size: 2rem;
          color: #ddd;
          cursor: pointer;
      }
      .rating input[type="radio"]:checked ~ label {
          color: #ffd700;
      }
      .rating label:hover,
      .rating label:hover ~ label {
          color: #ffd700;
      }
  </style>
    <title>Movie App</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-scroll shadow-0" style="background-color: #ffede7;">
        <div class="container">
          <a class="navbar-brand" href="#">Movies</a>
          <button class="navbar-toggler ps-0" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
            aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="d-flex justify-content-start align-items-center">
              <i class="fas fa-bars"></i>
            </span>
          </button>
          <div class="collapse navbar-collapse" id="navbarExample01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item active">
                <a class="nav-link px-3" href="{% url 'mywebsite:imdbtop' %}">IMDB Top 100</a>
              </li>
              <li class="nav-item">
                <a class="nav-link px-3" href="{% url 'mywebsite:intheaters' %}">Upcoming</a>
              </li>
              <li class="nav-item">
                <a class="nav-link px-3" href="{% url 'mywebsite:commentpage' %}">Comment Page</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link px-3" href="{% url 'mywebsite:whattowatch' %}">What to Watch?</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link px-3" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <form method="POST" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{% url 'mywebsite:imdbtop' %}">
                    <button type="submit" class="nav-link px-3" style="background: none; border: none; padding: 3; cursor: pointer;">Logout</button>
                </form>
            </li>
            <li class="nav-item">
              <a class="nav-link px-3" href="{% url 'mywebsite:signup' %}">SignUp</a>
            </li>
            
            
            
            </ul>
      
            <ul class="navbar-nav flex-row">
              <li class="nav-item">
                <a class="nav-link pe-3" href="https://www.youtube.com/@yalcinboradincer7313">
                  <i class="fab fa-youtube"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link px-3" href="https://github.com/YalcinBoraDincer">
                  <i class="fab fa-github"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link ps-3" href="https://www.instagram.com/dinceryalcinbora?igsh=M2U0bGgyb2FvMXM5">
                  <i class="fab fa-instagram"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
  {% block content %}
    {% endblock %}
    
</body>
</html>